// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVo4wrL1htBZ1Zx5-RUgzFxpC107cEG3U',
    appId: '1:455052147587:web:75486eb53b06d6310594b6',
    messagingSenderId: '455052147587',
    projectId: 'zisathil',
    authDomain: 'zisathil.firebaseapp.com',
    databaseURL: 'https://zisathil-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zisathil.firebasestorage.app',
    measurementId: 'G-HK4GZFWQ19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByTlEsku6Ber06nAtTaqQrvk9kMU3xHC0',
    appId: '1:455052147587:android:c6fe727e477e443f0594b6',
    messagingSenderId: '455052147587',
    projectId: 'zisathil',
    databaseURL: 'https://zisathil-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zisathil.firebasestorage.app',
  );
}
